# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
