# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0004_auto_20170808_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(),
        ),
    ]
